### ISSUE TITLE
交易demo切换评测版错误

### ISSUE THREAD

**Issue by ycsqyq** [Jedore/ctp.examples#1]
大佬你好，我在使用ctp.examples项目的openctp-ctp模块中的base_tdapi.py时，使用6.7.2在mac上是正常的（simnow），但是下单时提示：
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/d0cfd271-3b99-4e0d-b9d0-3b86deb87040">

更改open-ctp为open-ctp-cp时（6.7.0），并在linux上使用东航的地址和账号时报错
<img width="483" alt="image" src="https://github.com/user-attachments/assets/13ba2fef-cc78-4858-af6f-0c0ac8b8b5ea">

请问下这两种情况应该如何解决

**Comment by ycsqyq** [comment]
结算结果未确认的问题解决了（调用了查询结算及确认结算的接口），还有切换版本的问题麻烦大佬看下。。

**Comment by Jedore** [comment]
应该东航的这个环境，不是用的评测版吧？你试试

**Comment by ycsqyq** [comment]
用的是评测版，已经解决了，是因为mac机器下的"账号_td"缓存文件夹一起同步提交到linux下了，删除掉就好了，谢谢大佬
